### ISSUE TITLE
Using basic style stuff from Origami

### ISSUE THREAD

**Issue by dan-searle** [Financial-Times/x-dash#166]
What's our preferred approach to things like palette colours, where **o-colors** is (currently) the source of truth and provides SASS functions for getting colour values etc?

Some options:

* don't use **o-colors** - just hardcode colour values in x-dash components
* just install **o-colors** via bower in each component (have **bower** as a devDependency)
* change **o-colors** so it can be installed via npm
* add an **x-colors** x-dash component that installs **o-colors** via bower and makes a subset of its functionality available to other x-dash components (maybe via CSS variables?)
* something else?

**Comment by quarterto** [comment]
a very good point. i've seen this happening with typography styles as well. to quote childish gambino, "yeah yeah imma go into this":

there's a trade-off here between encapsulation and code reuse/deduplication. in one worst case scenario, styled x-dash components end up outputting the same shared (typography/button/etc) styles, and the more components you use on a page, the worse the bloat gets.

on the flip side, components reimplementing origami styles risks inconsistency, becoming stale, & going against brand/design guidelines. as a huge fan of origami that would make me very sad.

as the project has been growing we've been more worried about getting the first point right than the second, which is why so far we've advised against using origami bower modules. now we've got three+ components in the works with custom styling, we need to reconsider.

of your proposals, i'd prefer installing components with bower. getting origami components onto npm is going to happen, but not soon, and i would strongly prefer not to create x-dash components for the sole reason of wrapping origami components (we do not aim to replace origami).

last time i tried this was pre styling support in `x-rollup`, but for `x-follow-button`'s purposes that now supports loading Sass imports from `bower_components`. have a look at [that component](https://github.com/Financial-Times/x-dash/blob/a38ae39569a892f6445f09b34a76ce3734190e01/components/x-follow-button/package.json#L13) for the implementation (it is exactly what you describe though 🙂).

another option, which would work for `o-colors` but i don't know if any other module does this, would be to use its [CSS variables ](https://github.com/Financial-Times/o-colors#css-variables). you could even include it from the build service this way. this comes with the usual caveats of browser support, and we want to use more than just colours.

i would be much happier about this if we could somehow guarantee that components were always imported in silent mode and that (origami) components shared between (x-dash) components couldn't produce duplicate output. i could go on a rant here about how sass mixins are not the right tool for css code reuse and we should be using css modules everywhere but this reply is long enough already.

anyway yeah sorry for the wall of text. i think tl;dr would be "yeah sure use bower, don't use mixins too much, can't we live in the future already"

**Comment by dan-searle** [comment]
Thanks for taking the time to give a good overview, it really helps to understand the challenges.

I'll go with installing **o-colors** via bower then, and probably **o-typography** too. For **x-article-share-button** at least, there shouldn't be much that needs to be pulled in from Origami.

**Comment by i-like-robots** [comment]
Just to recap on a point t'other Matt made:

> in one worst case scenario, styled x-dash components end up outputting the same shared (typography/button/etc) styles, and the more components you use on a page, the worse the bloat gets.

This is currently how Origami components are authored as integration with other components is done using their mixins (the Origami spec bans the use of "foreign selectors", i.e. those declared within another module). This caveat does indeed make the styles bloated (hugely so 😢) but we do not yet have a better alternative.
