### ISSUE TITLE
CCPA cookie consent manager

### ISSUE THREAD

**Issue by oliverturner** [Financial-Times/x-dash#449]
## Description

As part of the work to achieve CCPA compliance the Privacy & Ads team has been asked to create a component to manage users' consent to their data for programmatic, demographic and behavioural advertising in a unified format per the requirements of the legislation.

This proposal is for a component that is available to FT.com, can be linked to from Specialist Titles, or rendered directly by the FT App.

## Design

![Screenshot 2020-05-13 at 09 18 11](https://user-images.githubusercontent.com/21795/81790310-249b0f80-94fd-11ea-9158-2bcb74eb7c50.png)

**Comment by apaleslimghost** [comment]
thanks Oliver! a few questions:

- is there an existing implementation anywhere, or is that a mockup?
- what state and behaviour does this component have? it looks like it's submitting a form in the background and displaying a success message?
- since this component will presumably only work while online, could the mobile Apps instead link to the FT.com implementation, rather than rendering it directly?
- will this component contain its own styling, or is it Origami-only?

**Comment by oliverturner** [comment]
Great questions!

- I started a quick spike to see how building the component in x-dash would be like: that's a screenshot of a story
- Re state and behaviour, spot on! That's exactly what it does, so I've wrapped the component in `withActions`
- Re linking to FT.com: the thinking behind rendering directly on FT App is that it simplifies cookie handling
- Re styling: the component uses custom CSS modules with Origami styles

**Comment by oliverturner** [comment]
Also worth noting that we're planning to unify the cookie consent management apps, so this component would be a great fit for future development.

**Comment by apaleslimghost** [comment]
yes, please push the branch and open a PR. sounds like this is a good fit for a component ✅
